# Generated by Django 4.2.27 on 2026-01-28 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daguerre', '0004_hash_upload_to_dir'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adjustedimage',
            new_name='daguerre_ad_request_fab777_idx',
            old_fields=('requested', 'storage_path'),
        ),
    ]
